name: ci
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Installing
        run: yarn --frozen-lockfile --link-duplicates --perfer-offline

      - name: Build
        run: yarn build

      - name: Archive lib
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: lib/

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn coverage

      - name: Send test coverage to codecov
        continue-on-error: true
        uses: codecov/codecov-action@v4

      - name: Functional tests (sqlite3)
        run: yarn test:sqlite3

      - name: Functional tests (postgres)
        env:
          POSTGRES_URL: postgres://postgres:postgres@localhost/postgres
        run: yarn test:postgres

  release:
    needs:
      - build
    if: |
      github.event_name == 'push' &&
      github.repository == 'SocialGouv/jest-environment-knex'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Download lib form build job
        uses: actions/download-artifact@v4
        with:
          name: lib
          path: lib

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN }}
